sudo: required

language: go

services:
  - docker

before_install:
  - docker build -t chrisruffalo/speedtrap .
  - docker run --name speedtrap -d -p 127.0.0.1:8000:80000 chrisruffalo/speedtrap
  - docker ps -a
  - docker rm -f speedtrap

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
